[package]
name = "rw-types"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rw-memory-derive = { path = "../rw-memory-derive" }
rw-operation-contract.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ts-rs.workspace = true

[lints]
workspace = true
