use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use rw_types::{
    AccountingAttribution, Answer, ApprovalBinding, ApprovalDecision, Attachment, AttachmentData,
    Block, BudgetLevel, BudgetScope, BudgetUnit, CacheBreakpoint, ClientCommand, ClientId,
    ClientRole, CommandAckMeta, CommandDescriptor, CommandMeta, CommandOutcome, CompactionReason,
    ContextItemId, ContextItemKind, ContextItemSnapshot, ContextItemState, ContextSnapshot, Cost,
    CostSnapshot, DiffArtifact, EngineError, EngineErrorCategory, EngineEvent, EventMeta, ImageRef,
    ModeId, ModelAlias, ModelCacheBehavior, ModelCapabilities, ModelDescriptor, PlanArtifact,
    PlanDecision, PlanStep, PromptDump, PromptTool, Question, QuestionId, QuestionOption,
    QuestionResponseKind, RequestId, RewindTarget, Role, SequenceId, SessionDescriptor, SessionId,
    ShellId, StoredAttachment, SubagentId, SubagentIsolation, SubagentResult, SubagentStatus,
    ToolCallId, ToolCapability, ToolOutput, ToolOutputPart, ToolOutputStream, TouchedFile,
    TouchedFileStatus, Turn, TurnAccounting, TurnId, TurnMeta, TurnStatus, UnifiedDiff,
    UnrestorablePath, Usage, WorkspaceFileMatch, WorkspaceFilePreview, WorkspaceRootDescriptor,
    WorkspaceStatus,
};
use schemars::{JsonSchema, schema_for};
use serde::Serialize;
use serde_json::json;
use thiserror::Error;
use ts_rs::{Config as TypeScriptConfig, TS};

#[derive(Debug, Error)]
enum XtaskError {
    #[error("usage: cargo xtask codegen [--check]")]
    Usage,
    #[error("could not read {path}: {source}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("could not write {path}: {source}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("could not serialize generated protocol artifact: {0}")]
    Serialize(#[from] serde_json::Error),
    #[error("generated artifact is stale: {0}")]
    Stale(PathBuf),
}

#[derive(Debug, Serialize)]
struct ContractFixture {
    turns: Vec<Turn>,
    client_commands: Vec<ClientCommand>,
    engine_events: Vec<EngineEvent>,
}

fn main() -> Result<(), XtaskError> {
    let mut arguments = env::args().skip(1);
    let Some(command) = arguments.next() else {
        return Err(XtaskError::Usage);
    };
    if command != "codegen" {
        return Err(XtaskError::Usage);
    }
    let check = match arguments.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(_) => return Err(XtaskError::Usage),
    };
    if arguments.next().is_some() {
        return Err(XtaskError::Usage);
    }

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let protocol = root.join("protocol");
    let artifacts = generated_artifacts()?;
    for (relative_path, contents) in artifacts {
        let path = protocol.join(relative_path);
        if check {
            check_artifact(&path, &contents)?;
        } else {
            write_artifact(&path, &contents)?;
        }
    }
    Ok(())
}

fn generated_artifacts() -> Result<Vec<(PathBuf, String)>, XtaskError> {
    let fixture = contract_fixture();
    Ok(vec![
        (PathBuf::from("types.ts"), generate_typescript()),
        (
            PathBuf::from("schema/block.schema.json"),
            generate_schema::<Block>()?,
        ),
        (
            PathBuf::from("schema/tool-output.schema.json"),
            generate_schema::<ToolOutput>()?,
        ),
        (
            PathBuf::from("schema/client-command.schema.json"),
            generate_schema::<ClientCommand>()?,
        ),
        (
            PathBuf::from("schema/engine-event.schema.json"),
            generate_schema::<EngineEvent>()?,
        ),
        (
            PathBuf::from("fixtures/contract.json"),
            serde_json::to_string_pretty(&fixture)? + "\n",
        ),
        (
            PathBuf::from("fixtures/contract.ts"),
            generate_typescript_fixture(&fixture)?,
        ),
    ])
}

fn generate_typescript_fixture(fixture: &ContractFixture) -> Result<String, serde_json::Error> {
    let fixture_json = serde_json::to_string_pretty(fixture)?;
    Ok(format!(
        "// @generated by `cargo xtask codegen`; do not edit by hand.\n\nimport type {{ ClientCommand, EngineEvent, Turn }} from \"../types\";\n\nexport const contractFixture = {fixture_json} satisfies {{\n  turns: Turn[];\n  client_commands: ClientCommand[];\n  engine_events: EngineEvent[];\n}};\n"
    ))
}

fn generate_typescript() -> String {
    let mut output =
        String::from("// @generated by `cargo xtask codegen`; do not edit by hand.\n\n");
    output.push_str(
        "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n",
    );
    output.push_str("export const PROTOCOL_VERSION = ");
    output.push_str(&rw_types::PROTOCOL_VERSION.to_string());
    output.push_str(" as const;\n\n");
    let typescript_config = TypeScriptConfig::default();

    macro_rules! declaration {
        ($type:ty) => {{
            output.push_str("export ");
            output.push_str(&<$type as TS>::decl(&typescript_config));
            output.push_str("\n\n");
        }};
    }

    declaration!(ToolCallId);
    declaration!(SessionId);
    declaration!(ClientId);
    declaration!(RequestId);
    declaration!(TurnId);
    declaration!(ShellId);
    declaration!(QuestionId);
    declaration!(SubagentId);
    declaration!(SubagentIsolation);
    declaration!(SubagentStatus);
    declaration!(TouchedFileStatus);
    declaration!(TouchedFile);
    declaration!(DiffArtifact);
    declaration!(SubagentResult);
    declaration!(ContextItemId);
    declaration!(ModelAlias);
    declaration!(SequenceId);
    declaration!(Role);
    declaration!(ImageRef);
    declaration!(ToolOutputPart);
    declaration!(ToolOutput);
    declaration!(Block);
    declaration!(TurnMeta);
    declaration!(Turn);
    declaration!(CommandMeta);
    declaration!(EventMeta);
    declaration!(CommandAckMeta);
    declaration!(ClientRole);
    declaration!(AttachmentData);
    declaration!(Attachment);
    declaration!(StoredAttachment);
    declaration!(SessionDescriptor);
    declaration!(CommandDescriptor);
    declaration!(ModelCacheBehavior);
    declaration!(ModelCapabilities);
    declaration!(ModelDescriptor);
    declaration!(WorkspaceFileMatch);
    declaration!(WorkspaceFilePreview);
    declaration!(WorkspaceStatus);
    declaration!(WorkspaceRootDescriptor);
    declaration!(UnifiedDiff);
    declaration!(ApprovalBinding);
    declaration!(ApprovalDecision);
    declaration!(ModeId);
    declaration!(PlanStep);
    declaration!(PlanArtifact);
    declaration!(PlanDecision);
    declaration!(RewindTarget);
    declaration!(QuestionResponseKind);
    declaration!(QuestionOption);
    declaration!(Question);
    declaration!(Answer);
    declaration!(ContextItemKind);
    declaration!(ContextItemState);
    declaration!(ContextItemSnapshot);
    declaration!(CacheBreakpoint);
    declaration!(ContextSnapshot);
    declaration!(AccountingAttribution);
    declaration!(TurnAccounting);
    declaration!(CostSnapshot);
    declaration!(PromptTool);
    declaration!(PromptDump);
    declaration!(ClientCommand);
    declaration!(ToolCapability);
    declaration!(ToolOutputStream);
    declaration!(TurnStatus);
    declaration!(CompactionReason);
    declaration!(BudgetUnit);
    declaration!(BudgetLevel);
    declaration!(BudgetScope);
    declaration!(Usage);
    declaration!(Cost);
    declaration!(UnrestorablePath);
    declaration!(EngineErrorCategory);
    declaration!(EngineError);
    declaration!(CommandOutcome);
    declaration!(EngineEvent);
    output
        .trim_end()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

fn generate_schema<T: JsonSchema>() -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(&schema_for!(T)).map(|schema| schema + "\n")
}

fn write_artifact(path: &Path, contents: &str) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| XtaskError::Write {
            path: parent.to_owned(),
            source,
        })?;
    }
    fs::write(path, contents).map_err(|source| XtaskError::Write {
        path: path.to_owned(),
        source,
    })
}

fn check_artifact(path: &Path, expected: &str) -> Result<(), XtaskError> {
    let actual = fs::read_to_string(path).map_err(|source| XtaskError::Read {
        path: path.to_owned(),
        source,
    })?;
    if actual == expected {
        Ok(())
    } else {
        Err(XtaskError::Stale(path.to_owned()))
    }
}

#[allow(clippy::too_many_lines)]
fn contract_fixture() -> ContractFixture {
    let command_meta = CommandMeta {
        protocol_version: rw_types::PROTOCOL_VERSION,
        client_id: ClientId("client-fixture".to_owned()),
        request_id: RequestId("request-fixture".to_owned()),
    };
    let event_meta = |sequence_id| EventMeta {
        protocol_version: rw_types::PROTOCOL_VERSION,
        session_id: SessionId("session-fixture".to_owned()),
        sequence_id: SequenceId(sequence_id),
        emitted_at: "2026-01-01T00:00:00Z".to_owned(),
        caused_by: None,
    };
    let subagent_result = |id: &str, session: &str, text: &str| SubagentResult {
        subagent_id: SubagentId(id.to_owned()),
        session_id: SessionId(session.to_owned()),
        status: SubagentStatus::Completed,
        final_text: text.to_owned(),
        touched_files: Vec::new(),
        diff_artifact: None,
        usage: Usage {
            input_tokens: 10,
            output_tokens: 5,
            cache_read_tokens: 0,
            cache_write_tokens: 0,
            reasoning_tokens: 0,
        },
        cost: Cost::Unavailable {
            reason: "fixture".to_owned(),
        },
        turns: 1,
        duration_millis: 5,
    };
    let mixed_output = ToolOutput::Mixed {
        parts: vec![
            ToolOutputPart::Text {
                text: "build output".to_owned(),
            },
            ToolOutputPart::Structured {
                value: json!({"passed": 3, "failed": 0}),
            },
            ToolOutputPart::Image {
                media_type: "image/png".to_owned(),
                data: ImageRef::InlineBase64 {
                    data: "iVBORw0KGgo=".to_owned(),
                },
            },
        ],
    };
    let turn = Turn {
        role: Role::Assistant,
        blocks: vec![
            Block::Text {
                text: "Working".to_owned(),
            },
            Block::Thinking {
                content: "Check the repository".to_owned(),
                signature: Some("opaque-signature".to_owned()),
            },
            Block::ToolCall {
                id: ToolCallId("tool-1".to_owned()),
                name: "bash".to_owned(),
                args: json!({"command": "cargo test"}),
            },
            Block::ToolResult {
                id: ToolCallId("tool-1".to_owned()),
                output: mixed_output.clone(),
                is_error: false,
            },
            Block::Image {
                media_type: "image/png".to_owned(),
                data: ImageRef::Url {
                    url: "https://example.invalid/image.png".to_owned(),
                },
            },
            Block::Citation {
                uri: "https://example.invalid/source".to_owned(),
                title: Some("Source".to_owned()),
                excerpt: None,
            },
        ],
        meta: TurnMeta {
            created_at: Some("2026-01-01T00:00:00Z".to_owned()),
            model: Some("fast".to_owned()),
            synthetic: false,
            summary: false,
        },
    };
    let plan_artifact = PlanArtifact {
        title: "Protocol plan".to_owned(),
        summary_md: "Exercise the durable plan contract.".to_owned(),
        steps: vec![PlanStep {
            description: "Verify generated clients".to_owned(),
            files_touched: vec!["protocol/types.ts".to_owned()],
            verification: "cargo xtask codegen --check".to_owned(),
        }],
        open_questions: Vec::new(),
    };

    ContractFixture {
        turns: vec![turn],
        client_commands: vec![
            ClientCommand::CreateSession {
                meta: command_meta.clone(),
                cwd: "workspace".to_owned(),
                model: Some(ModelAlias("fast".to_owned())),
            },
            ClientCommand::SendMessage {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                content: "Build it".to_owned(),
                attachments: Vec::new(),
            },
            ClientCommand::AttachSession {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                last_seen_sequence: Some(SequenceId(4)),
                role: ClientRole::Observer,
            },
            ClientCommand::AttachSession {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                last_seen_sequence: None,
                role: ClientRole::Driver,
            },
            ClientCommand::SendMessage {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                content: "Inspect these".to_owned(),
                attachments: vec![
                    Attachment {
                        name: "notes.txt".to_owned(),
                        media_type: "text/plain".to_owned(),
                        data: AttachmentData::Text {
                            content: "in-band text".to_owned(),
                        },
                    },
                    Attachment {
                        name: "screen.png".to_owned(),
                        media_type: "image/png".to_owned(),
                        data: AttachmentData::InlineBase64 {
                            data: "iVBORw0KGgo=".to_owned(),
                        },
                    },
                ],
            },
            ClientCommand::ApproveTool {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                tool_call_id: ToolCallId("tool-1".to_owned()),
                decision: ApprovalDecision::AllowOnce,
                binding: None,
            },
            ClientCommand::ApprovePlan {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                decision: PlanDecision::Approve,
                revisions: None,
            },
            ClientCommand::AnswerQuestion {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                question_id: QuestionId("question-1".to_owned()),
                answers: vec![Answer {
                    question_id: QuestionId("question-1".to_owned()),
                    values: vec!["yes".to_owned()],
                }],
            },
            ClientCommand::Interrupt {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
            },
            ClientCommand::SwitchMode {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                mode: ModeId("plan".to_owned()),
            },
            ClientCommand::SwitchModel {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                model: ModelAlias("fast".to_owned()),
            },
            ClientCommand::Compact {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                instructions: None,
            },
            ClientCommand::Fork {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                at_turn: None,
            },
            ClientCommand::Rewind {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                target: RewindTarget::Turn {
                    turn_id: TurnId("turn-fixture".to_owned()),
                },
            },
            ClientCommand::Rewind {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                target: RewindTarget::Checkpoint {
                    checkpoint_id: "checkpoint-1".to_owned(),
                },
            },
            ClientCommand::TakeDriver {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
            },
            ClientCommand::UserShellStarted {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                command: "python".to_owned(),
            },
            ClientCommand::UserShellEnded {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                shell_id: ShellId("shell-fixture".to_owned()),
                status: 0,
                captured_output: None,
            },
            ClientCommand::PinContext {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                item_id: ContextItemId("context-1".to_owned()),
            },
            ClientCommand::EvictContext {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
                item_id: ContextItemId("context-2".to_owned()),
            },
            ClientCommand::GetContext {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
            },
            ClientCommand::GetCost {
                meta: command_meta.clone(),
                session_id: SessionId("session-fixture".to_owned()),
            },
            ClientCommand::DumpPrompt {
                meta: command_meta,
                session_id: SessionId("session-fixture".to_owned()),
                turn_id: Some(TurnId("turn-fixture".to_owned())),
            },
        ],
        engine_events: vec![
            EngineEvent::CommandAcknowledged {
                meta: CommandAckMeta {
                    protocol_version: rw_types::PROTOCOL_VERSION,
                    client_id: ClientId("client-fixture".to_owned()),
                    request_id: RequestId("request-fixture".to_owned()),
                    emitted_at: "2026-01-01T00:00:00Z".to_owned(),
                },
                session_id: Some(SessionId("session-fixture".to_owned())),
                outcome: CommandOutcome::Accepted,
            },
            EngineEvent::CommandAcknowledged {
                meta: CommandAckMeta {
                    protocol_version: rw_types::PROTOCOL_VERSION,
                    client_id: ClientId("client-fixture".to_owned()),
                    request_id: RequestId("rejected-request".to_owned()),
                    emitted_at: "2026-01-01T00:00:00Z".to_owned(),
                },
                session_id: None,
                outcome: CommandOutcome::Rejected {
                    error: EngineError {
                        category: EngineErrorCategory::Protocol,
                        code: "invalid_command".to_owned(),
                        message: "command was rejected".to_owned(),
                        retryable: false,
                        details: None,
                    },
                },
            },
            EngineEvent::SessionCreated {
                meta: event_meta(0),
                driver_client_id: ClientId("client-fixture".to_owned()),
            },
            EngineEvent::DriverChanged {
                meta: event_meta(1),
                driver_client_id: ClientId("client-fixture".to_owned()),
            },
            EngineEvent::TurnStarted {
                meta: event_meta(2),
                turn_id: TurnId("turn-fixture".to_owned()),
            },
            EngineEvent::TextDelta {
                meta: event_meta(3),
                turn_id: TurnId("turn-fixture".to_owned()),
                text: "hello".to_owned(),
            },
            EngineEvent::ThinkingDelta {
                meta: event_meta(4),
                turn_id: TurnId("turn-fixture".to_owned()),
                text: "checking".to_owned(),
                signature: None,
            },
            EngineEvent::ToolCallStarted {
                meta: event_meta(5),
                turn_id: TurnId("turn-fixture".to_owned()),
                tool_call_id: ToolCallId("tool-1".to_owned()),
                name: "bash".to_owned(),
                args: json!({"command": "cargo test"}),
                call_index: 0,
            },
            EngineEvent::ToolApprovalNeeded {
                meta: event_meta(6),
                turn_id: TurnId("turn-fixture".to_owned()),
                tool_call_id: ToolCallId("tool-1".to_owned()),
                name: "bash".to_owned(),
                args: json!({"command": "cargo test"}),
                capabilities: vec![ToolCapability::Execute],
                rationale: "runs a local command".to_owned(),
                diff: None,
            },
            EngineEvent::ToolOutputDelta {
                meta: event_meta(7),
                turn_id: TurnId("turn-fixture".to_owned()),
                tool_call_id: ToolCallId("tool-1".to_owned()),
                stream: ToolOutputStream::Stdout,
                chunk: "running tests".to_owned(),
            },
            EngineEvent::ToolCallFinished {
                meta: event_meta(8),
                turn_id: TurnId("turn-fixture".to_owned()),
                tool_call_id: ToolCallId("tool-1".to_owned()),
                output: mixed_output,
                is_error: false,
                call_index: 0,
            },
            EngineEvent::QuestionAsked {
                meta: event_meta(9),
                turn_id: TurnId("turn-fixture".to_owned()),
                question_id: QuestionId("question-1".to_owned()),
                questions: vec![Question {
                    id: QuestionId("question-1".to_owned()),
                    prompt: "Continue?".to_owned(),
                    response_kind: QuestionResponseKind::SelectOne,
                    options: vec![QuestionOption {
                        value: "yes".to_owned(),
                        label: "Yes".to_owned(),
                        description: None,
                    }],
                }],
            },
            EngineEvent::QuestionAnswered {
                meta: event_meta(10),
                turn_id: TurnId("turn-fixture".to_owned()),
                question_id: QuestionId("question-1".to_owned()),
                answers: vec![Answer {
                    question_id: QuestionId("question-1".to_owned()),
                    values: vec!["yes".to_owned()],
                }],
            },
            EngineEvent::TurnFinished {
                meta: event_meta(11),
                turn_id: TurnId("turn-fixture".to_owned()),
                status: TurnStatus::Completed,
                usage: Usage {
                    input_tokens: 100,
                    output_tokens: 20,
                    cache_read_tokens: 80,
                    cache_write_tokens: 0,
                    reasoning_tokens: 5,
                },
                cost: Cost::Monetary {
                    amount_micros: 125,
                    currency: "USD".to_owned(),
                },
            },
            EngineEvent::CompactionStarted {
                meta: event_meta(12),
                reason: CompactionReason::Automatic,
            },
            EngineEvent::CompactionFinished {
                meta: event_meta(13),
                summary_turn_id: TurnId("summary-turn".to_owned()),
                reclaimed_tokens: 25_000,
                usage: None,
                cost: None,
            },
            EngineEvent::SubagentSpawned {
                meta: event_meta(14),
                subagent_id: SubagentId("subagent-1".to_owned()),
                child_session_id: SessionId("child-session-1".to_owned()),
                task: "inspect protocol".to_owned(),
            },
            EngineEvent::SubagentFinished {
                meta: event_meta(15),
                subagent_id: SubagentId("subagent-1".to_owned()),
                result: subagent_result("subagent-1", "child-session-1", "done"),
            },
            EngineEvent::SubagentFinished {
                meta: event_meta(16),
                subagent_id: SubagentId("subagent-2".to_owned()),
                result: subagent_result("subagent-2", "child-session-2", "three files"),
            },
            EngineEvent::ToolOutputPruned {
                meta: event_meta(17),
                tool_call_id: ToolCallId("tool-old".to_owned()),
                reclaimed_tokens: 21_000,
            },
            EngineEvent::ModeChanged {
                meta: event_meta(18),
                mode: ModeId("plan".to_owned()),
            },
            EngineEvent::ModelChanged {
                meta: event_meta(19),
                model: ModelAlias("fast".to_owned()),
            },
            EngineEvent::ContextItemPinned {
                meta: event_meta(20),
                item_id: ContextItemId("context-1".to_owned()),
                effective_after_agent_turn: 3,
            },
            EngineEvent::ContextItemEvicted {
                meta: event_meta(21),
                item_id: ContextItemId("context-2".to_owned()),
                effective_after_agent_turn: 3,
            },
            EngineEvent::UserShellStateChanged {
                meta: event_meta(22),
                shell_id: ShellId("shell-fixture".to_owned()),
                command: Some("python".to_owned()),
                active: false,
                status: None,
                captured_output: None,
            },
            EngineEvent::Error {
                meta: event_meta(23),
                error: EngineError {
                    category: EngineErrorCategory::Protocol,
                    code: "invalid_command".to_owned(),
                    message: "command was rejected".to_owned(),
                    retryable: false,
                    details: Some(json!({"field": "type"})),
                },
            },
            EngineEvent::PlanSubmitted {
                meta: event_meta(24),
                artifact: plan_artifact.clone(),
            },
            EngineEvent::PlanReviewed {
                meta: event_meta(25),
                artifact: plan_artifact,
                decision: PlanDecision::Approve,
                revisions: None,
            },
        ],
    }
}
