mod shared_types;
use std::fs;
use std::path::{Path, PathBuf};

use rw_operation_contract::{
    DEFAULT_TOOL_IDLE_TIMEOUT_MS, MAX_PROGRESS_FRAME_BYTES, MAX_PROGRESS_MESSAGE_BYTES,
    MAX_PROGRESS_MESSAGE_CHARS, OperationLifetime, PROGRESS_BURST, PROGRESS_INTERVAL_MS,
    ProgressAmount, ToolProgress,
};
use rw_plugin_protocol::{
    CONTROL_QUEUE_BYTES, CONTROL_QUEUE_FRAMES, DATA_QUEUE_BYTES, DEFAULT_HANDLER_TIMEOUT_MS,
    JSON_RPC_VERSION, MAX_CAPABILITIES_PER_KIND, MAX_DESCRIPTION_BYTES, MAX_FRAME_BYTES,
    MAX_HOOK_PAYLOAD_BYTES, MAX_IN_FLIGHT_REQUESTS, MAX_MANIFEST_BYTES, MAX_NAME_BYTES,
    MAX_OPERATION_DURATION_MS, MAX_PLUGIN_MODEL_TOKENS, MAX_PLUGIN_PRICE_MICROS_USD,
    MAX_PROVIDER_STREAMS, MAX_RPC_MESSAGE_BYTES, MAX_SCHEMA_BYTES, MAX_SCHEMA_DEPTH,
    MAX_VERSION_BYTES, METHOD_COMMAND_EXECUTE, METHOD_EVENT_PUBLISH, METHOD_EVENT_READ,
    METHOD_EXIT, METHOD_EXTENSION_STATE_COMMIT, METHOD_EXTENSION_STATE_READ, METHOD_HOOK_INVOKE,
    METHOD_INITIALIZE, METHOD_PROVIDER_COMPLETE, METHOD_PROVIDER_CREDIT, METHOD_PROVIDER_EVENT,
    METHOD_PROVIDER_HTTP, METHOD_PROVIDER_HTTP_CANCEL, METHOD_PROVIDER_HTTP_EVENT,
    METHOD_PROVIDER_MODELS, METHOD_SESSION_CONTEXT_READ, METHOD_SESSION_CONTROL,
    METHOD_SESSION_INJECT_MESSAGE, METHOD_SESSION_QUERY, METHOD_SESSION_SET_STATUS,
    METHOD_SESSION_TOOL_CALL, METHOD_SHUTDOWN, METHOD_TOOL_CALL, METHOD_TOOL_PROGRESS,
    METHOD_UI_NOTIFY, METHOD_UI_PUBLISH_PANEL, PLUGIN_HOST_ID, PROTOCOL_VERSION,
    PROVIDER_WINDOW_BYTES, PROVIDER_WINDOW_EVENTS,
};
use serde_json::{Value, json};
use ts_rs::TS;

const GENERATED_NOTICE: &str = "@generated by cargo xtask codegen; do not edit by hand.";
const GENERATED_MARKER: &str = "// @generated by cargo xtask codegen; do not edit by hand.";
const TYPESCRIPT_DECLARATIONS: &str = r#"export type JsonPrimitive = boolean | number | string | null
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue }
export type JsonObject = { [key: string]: JsonValue }
export type JsonSchema = JsonObject

export type ToolCapability = "reads-fs" | "writes-fs" | "network" | "exec"

export interface ToolDeclaration {
  readonly name: string
  readonly description: string
  readonly schema: JsonSchema
  readonly caps: readonly ToolCapability[]
}

export interface CommandDeclaration {
  readonly name: string
  readonly description: string
  readonly argument_hint?: string
  readonly allowed_tools?: readonly string[]
}

import type { HookEvent, HookClass, HookFailurePolicy } from "./hook-contract"
export type { HookEvent, HookClass, HookFailurePolicy, HookInput, HookDirective, HookTransform, HookPermissionDecision } from "./hook-contract"

export interface HookDeclaration {
  readonly name: HookEvent
  readonly class: HookClass
  readonly failure_policy: HookFailurePolicy
}

export interface ProviderDeclaration {
  readonly "alias-prefix": string
  /** Approval-fingerprinted provider RPC capabilities. Protocol 3 defines `models`. */
  readonly capabilities?: readonly string[]
  /** Approval-fingerprinted credential references. Values remain host-only. */
  readonly "credential-references"?: readonly string[]
}

import type { ExtensionEventKind } from "./extension-contract"
export type { ExtensionEventKind, ExtensionEventNotice, ExtensionEventOutcome, ExtensionEventRead, ExtensionEventChunk } from "./extension-contract"

export type PluginPushMethod =
  | "event/read"
  | "session/query"
  | "session/context_read"
  | "session/control"
  | "session/tool_call"
  | "extension/state_read"
  | "extension/state_commit"
  | "session/inject_message"
  | "session/set_status"
  | "ui/notify"
  | "ui/publish_panel"

import type { UiContribution } from "./ui-contract"
export type { UiContribution } from "./ui-contract"

export interface PluginCapabilities {
  readonly ui?: readonly UiContribution[]
  readonly tools?: readonly ToolDeclaration[]
  readonly commands?: readonly CommandDeclaration[]
  readonly hooks?: readonly HookDeclaration[]
  readonly providers?: readonly ProviderDeclaration[]
  readonly event_subscriptions?: readonly ExtensionEventKind[]
  readonly push?: readonly PluginPushMethod[]
}

export interface PluginManifest {
  readonly name: string
  readonly version: string
  readonly protocol: typeof PLUGIN_PROTOCOL_VERSION
  readonly capabilities: PluginCapabilities
}

export interface InitializeParams {
  readonly host: string
  readonly protocol: number
  readonly max_frame_bytes: number
  readonly capabilities?: readonly string[]
}

export interface ProviderModelsParams {
  readonly alias_prefix: string
}

export type ProviderCacheBreakpoints = "none" | "explicit" | "automatic"

export interface ProviderModelCapabilities {
  readonly tool_calling: boolean
  readonly vision: boolean
  readonly thinking: boolean
  readonly cache_breakpoints: ProviderCacheBreakpoints
}

export interface ProviderModelPricing {
  readonly input_per_million_micros_usd: number
  readonly output_per_million_micros_usd: number
  readonly cache_read_per_million_micros_usd?: number
  readonly cache_write_per_million_micros_usd?: number
  readonly reasoning_per_million_micros_usd?: number
}

export interface ProviderModel {
  readonly id: string
  readonly display_name?: string
  readonly capabilities: ProviderModelCapabilities
  readonly max_context_tokens?: number
  readonly max_output_tokens?: number
  readonly pricing?: ProviderModelPricing
}

export interface ProviderModelsResponse {
  readonly models: readonly ProviderModel[]
}

export interface InjectMessageResult {
  readonly disposition: "started" | "queued" | "command"
}

export interface ToolCallParams {
  readonly name: string
  readonly input: JsonObject
  readonly lifetime: OperationLifetime
}

export interface ToolProgressParams {
  readonly request_id: RpcId
  readonly sequence: number
  readonly progress: ToolProgress
}

export type { ToolResponse } from "./tool-contract"

export interface CommandExecuteParams {
  readonly lifetime: OperationLifetime
  readonly invocation_id: import("./extension-contract").ExtensionInvocationId | null
  readonly name: string
  readonly arguments: string
}

import type { ProviderRequest, ProviderEvent } from "./provider-contract"
export type { ProviderRequest, ProviderEvent, Turn, TurnMeta, Role, Block, ToolOutput, ToolOutputPart, ImageRef, ToolDefinition, ToolChoice, CacheHint, TokenUsage, FinishReason, ThinkingLevel } from "./provider-contract"

export interface ProviderCompleteParams {
  readonly alias: string
  readonly request: ProviderRequest
}

export interface ProviderCreditParams {
  readonly request_id: RpcId
  readonly events: number
  readonly bytes: number
}

export interface ProviderEventParams {
  readonly request_id: RpcId
  readonly event: ProviderEvent
}

export interface ProviderHttpCancelParams {
  readonly request_id: RpcId
}

export interface ProviderHttpHeader {
  readonly name: string
  readonly value: string
}

export interface ProviderHttpRequest {
  readonly method: "GET" | "POST" | "DELETE"
  readonly url: string
  readonly headers?: readonly ProviderHttpHeader[]
  readonly body?: Uint8Array
  readonly credential_header: string
  readonly credential_prefix?: string
}

export interface ProviderHttpResponse {
  readonly status: number
  readonly headers: readonly ProviderHttpHeader[]
  readonly body: AsyncIterable<Uint8Array>
}

export type ProviderStream = AsyncIterable<ProviderEvent>

export type RpcId = number | string

export interface RpcRequest {
  readonly jsonrpc: "2.0"
  readonly id: RpcId
  readonly method: string
  readonly params?: JsonValue
}

export interface RpcNotification {
  readonly jsonrpc: "2.0"
  readonly method: string
  readonly params?: JsonValue
}

export interface RpcErrorObject {
  readonly code: number
  readonly message: string
  readonly data?: JsonValue
}

export type RpcResponse =
  | { readonly jsonrpc: "2.0"; readonly id: RpcId; readonly result: JsonValue }
  | { readonly jsonrpc: "2.0"; readonly id: RpcId | null; readonly error: RpcErrorObject }
"#;
const FIXTURE_TEMPLATE: &str = r#"{
  "protocol": 3,
  "status": "stable",
  "framing": "newline-delimited-json-rpc-2.0",
  "limits": {
    "max_frame_bytes": 4194304,
    "max_manifest_bytes": 262144,
    "max_capabilities_per_kind": 256,
    "max_name_bytes": 128,
    "max_version_bytes": 64,
    "max_description_bytes": 16384,
    "max_schema_bytes": 65536,
    "max_schema_depth": 32,
    "max_model_tokens": 16777216,
    "max_price_micros_usd": 1000000000000
  },
  "methods": {
    "initialize": "initialize",
    "toolCall": "tool/call",
    "commandExecute": "command/execute",
    "hookInvoke": "hook/invoke",
    "providerComplete": "provider/complete",
    "providerModels": "provider/models",
    "providerEvent": "provider/event",
    "providerHttp": "provider/http",
    "providerHttpEvent": "provider/http_event",
    "providerHttpCancel": "provider/http_cancel",
    "eventPublish": "event/publish",
    "eventRead": "event/read",
    "injectMessage": "session/inject_message",
    "setStatus": "session/set_status",
    "notify": "ui/notify",
    "shutdown": "shutdown",
    "exit": "exit"
  },
  "initialize_request": {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
      "host": "rottweiler",
      "protocol": 3,
      "max_frame_bytes": 4194304,
      "capabilities": ["provider-models", "provider-http"]
    }
  },
  "initialize_response": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "name": "wire-fixture-v3",
      "version": "1.0.0",
      "protocol": 3,
      "capabilities": {
        "providers": [{
          "alias-prefix": "fixture-v3/",
          "capabilities": ["models"],
          "credential-references": ["fixture-token"]
        }]
      }
    }
  },
  "provider_models_request": {
    "jsonrpc": "2.0",
    "id": 2,
    "method": "provider/models",
    "params": { "alias_prefix": "fixture-v3/" }
  },
  "provider_models_response": {
    "jsonrpc": "2.0",
    "id": 2,
    "result": {
      "models": [{
        "id": "vision-thinking",
        "display_name": "Vision Thinking",
        "capabilities": {
          "tool_calling": true,
          "vision": true,
          "thinking": true,
          "cache_breakpoints": "explicit"
        },
        "max_context_tokens": 200000,
        "max_output_tokens": 16000,
        "pricing": {
          "input_per_million_micros_usd": 3000000,
          "output_per_million_micros_usd": 15000000,
          "cache_read_per_million_micros_usd": 300000,
          "cache_write_per_million_micros_usd": 3750000
        }
      }]
    }
  },
  "provider_http_request": {
    "jsonrpc": "2.0",
    "id": "plugin-http-1",
    "method": "provider/http",
    "params": {
      "alias": "fixture-v3/vision-thinking",
      "credential_reference": "fixture-token",
      "request": {
        "method": "POST",
        "url": "https://api.example.test/v1/complete",
        "headers": [{ "name": "content-type", "value": "application/json" }],
        "body_base64": "e30=",
        "credential_header": "authorization",
        "credential_prefix": "Bearer "
      }
    }
  },
  "provider_http_head": {
    "jsonrpc": "2.0",
    "method": "provider/http_event",
    "params": {
      "request_id": "plugin-http-1",
      "event": { "type": "head", "status": 200, "headers": [["content-type", "text/event-stream"]] }
    }
  },
  "provider_http_body": {
    "jsonrpc": "2.0",
    "method": "provider/http_event",
    "params": {
      "request_id": "plugin-http-1",
      "event": { "type": "body", "data_base64": "ZGF0YToge30K" }
    }
  },
  "provider_http_finished": {
    "jsonrpc": "2.0",
    "method": "provider/http_event",
    "params": { "request_id": "plugin-http-1", "event": { "type": "finished" } }
  }
}"#;
const SCHEMA_TEMPLATE: &str = r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://rottweiler.dev/schema/plugin/protocol-3.json",
  "title": "Rottweiler Plugin API conformance fixture",
  "type": "object",
  "required": ["protocol", "status", "framing", "limits", "methods", "initialize_request", "initialize_response", "provider_models_request", "provider_models_response", "provider_http_request", "provider_http_head", "provider_http_body", "provider_http_finished"],
  "properties": {
    "protocol": { "const": 2 },
    "status": { "const": "stable" },
    "framing": { "const": "newline-delimited-json-rpc-2.0" },
    "limits": {
      "type": "object",
      "required": ["max_frame_bytes", "max_manifest_bytes", "max_capabilities_per_kind", "max_name_bytes", "max_version_bytes", "max_description_bytes", "max_schema_bytes", "max_schema_depth", "max_model_tokens", "max_price_micros_usd"],
      "properties": {
        "max_frame_bytes": { "const": 4194304 },
        "max_manifest_bytes": { "const": 262144 },
        "max_capabilities_per_kind": { "const": 256 },
        "max_name_bytes": { "const": 128 },
        "max_version_bytes": { "const": 64 },
        "max_description_bytes": { "const": 16384 },
        "max_schema_bytes": { "const": 65536 },
        "max_schema_depth": { "const": 32 },
        "max_model_tokens": { "const": 16777216 },
        "max_price_micros_usd": { "const": 1000000000000 }
      },
      "additionalProperties": false
    },
    "methods": { "type": "object" },
    "initialize_request": { "$ref": "#/$defs/request" },
    "initialize_response": { "$ref": "#/$defs/success" },
    "provider_models_request": { "$ref": "#/$defs/request" },
    "provider_models_response": { "$ref": "#/$defs/success" },
    "provider_http_request": { "$ref": "#/$defs/request" },
    "provider_http_head": { "$ref": "#/$defs/notification" },
    "provider_http_body": { "$ref": "#/$defs/notification" },
    "provider_http_finished": { "$ref": "#/$defs/notification" }
  },
  "additionalProperties": false,
  "$defs": {
    "id": { "oneOf": [{ "type": "integer" }, { "type": "string", "minLength": 1, "maxLength": 128 }] },
    "request": {
      "type": "object",
      "required": ["jsonrpc", "id", "method"],
      "properties": {
        "jsonrpc": { "const": "2.0" },
        "id": { "$ref": "#/$defs/id" },
        "method": { "type": "string", "minLength": 1, "maxLength": 128 },
        "params": true
      },
      "additionalProperties": false
    },
    "success": {
      "type": "object",
      "required": ["jsonrpc", "id", "result"],
      "properties": {
        "jsonrpc": { "const": "2.0" },
        "id": { "$ref": "#/$defs/id" },
        "result": true
      },
      "additionalProperties": false
    },
    "notification": {
      "type": "object",
      "required": ["jsonrpc", "method"],
      "properties": {
        "jsonrpc": { "const": "2.0" },
        "method": { "type": "string", "minLength": 1, "maxLength": 128 },
        "params": true
      },
      "additionalProperties": false
    },
    "provider_capability": { "type": "string", "pattern": "^[a-z0-9_.-]+$", "maxLength": 128 },
    "provider_declaration": {
      "type": "object",
      "required": ["alias-prefix"],
      "properties": {
        "alias-prefix": { "type": "string", "pattern": "^[a-z0-9_.-]+/$", "maxLength": 128 },
        "capabilities": {
          "type": "array",
          "maxItems": 256,
          "uniqueItems": true,
          "items": { "$ref": "#/$defs/provider_capability" }
        },
        "credential-references": {
          "type": "array",
          "maxItems": 256,
          "uniqueItems": true,
          "items": { "$ref": "#/$defs/provider_capability" }
        }
      },
      "additionalProperties": false
    },
    "model_capabilities": {
      "type": "object",
      "required": ["tool_calling", "vision", "thinking", "cache_breakpoints"],
      "properties": {
        "tool_calling": { "type": "boolean" },
        "vision": { "type": "boolean" },
        "thinking": { "type": "boolean" },
        "cache_breakpoints": { "enum": ["none", "explicit", "automatic"] }
      },
      "additionalProperties": false
    },
    "pricing": {
      "type": "object",
      "required": ["input_per_million_micros_usd", "output_per_million_micros_usd"],
      "properties": {
        "input_per_million_micros_usd": { "type": "integer", "minimum": 0, "maximum": 1000000000000 },
        "output_per_million_micros_usd": { "type": "integer", "minimum": 0, "maximum": 1000000000000 },
        "cache_read_per_million_micros_usd": { "type": "integer", "minimum": 0, "maximum": 1000000000000 },
        "cache_write_per_million_micros_usd": { "type": "integer", "minimum": 0, "maximum": 1000000000000 },
        "reasoning_per_million_micros_usd": { "type": "integer", "minimum": 0, "maximum": 1000000000000 }
      },
      "additionalProperties": false
    },
    "model": {
      "type": "object",
      "required": ["id", "capabilities"],
      "properties": {
        "id": { "type": "string", "minLength": 1, "maxLength": 128 },
        "display_name": { "type": "string", "minLength": 1, "maxLength": 128 },
        "capabilities": { "$ref": "#/$defs/model_capabilities" },
        "max_context_tokens": { "type": "integer", "minimum": 1, "maximum": 16777216 },
        "max_output_tokens": { "type": "integer", "minimum": 1, "maximum": 16777216 },
        "pricing": { "$ref": "#/$defs/pricing" }
      },
      "additionalProperties": false
    },
    "provider_models_result": {
      "type": "object",
      "required": ["models"],
      "properties": {
        "models": { "type": "array", "maxItems": 256, "items": { "$ref": "#/$defs/model" } }
      },
      "additionalProperties": false
    }
  }
}"##;

fn methods() -> Value {
    json!({
        "initialize": METHOD_INITIALIZE,
        "toolCall": METHOD_TOOL_CALL,
        "toolProgress": METHOD_TOOL_PROGRESS,
        "commandExecute": METHOD_COMMAND_EXECUTE,
        "hookInvoke": METHOD_HOOK_INVOKE,
        "providerComplete": METHOD_PROVIDER_COMPLETE,
        "providerModels": METHOD_PROVIDER_MODELS,
        "providerEvent": METHOD_PROVIDER_EVENT,
        "providerCredit": METHOD_PROVIDER_CREDIT,
        "providerHttp": METHOD_PROVIDER_HTTP,
        "providerHttpEvent": METHOD_PROVIDER_HTTP_EVENT,
        "providerHttpCancel": METHOD_PROVIDER_HTTP_CANCEL,
        "eventPublish": METHOD_EVENT_PUBLISH,
        "eventRead": METHOD_EVENT_READ,
        "sessionQuery": METHOD_SESSION_QUERY,
        "contextRead": METHOD_SESSION_CONTEXT_READ,
        "sessionControl": METHOD_SESSION_CONTROL,
        "sessionToolCall": METHOD_SESSION_TOOL_CALL,
        "stateRead": METHOD_EXTENSION_STATE_READ,
        "stateCommit": METHOD_EXTENSION_STATE_COMMIT,
        "injectMessage": METHOD_SESSION_INJECT_MESSAGE,
        "setStatus": METHOD_SESSION_SET_STATUS,
        "notify": METHOD_UI_NOTIFY,
        "publishPanel": METHOD_UI_PUBLISH_PANEL,
        "shutdown": METHOD_SHUTDOWN,
        "exit": METHOD_EXIT,
    })
}

fn limits() -> Value {
    json!({
        "max_frame_bytes": MAX_FRAME_BYTES,
        "max_provider_streams": MAX_PROVIDER_STREAMS,
        "max_in_flight_requests": MAX_IN_FLIGHT_REQUESTS,
        "provider_window_events": PROVIDER_WINDOW_EVENTS,
        "provider_window_bytes": PROVIDER_WINDOW_BYTES,
        "control_queue_frames": CONTROL_QUEUE_FRAMES,
        "control_queue_bytes": CONTROL_QUEUE_BYTES,
        "data_queue_bytes": DATA_QUEUE_BYTES,
        "max_operation_duration_ms": MAX_OPERATION_DURATION_MS,
        "default_tool_idle_timeout_ms": DEFAULT_TOOL_IDLE_TIMEOUT_MS,
        "max_progress_message_chars": MAX_PROGRESS_MESSAGE_CHARS,
        "max_progress_message_bytes": MAX_PROGRESS_MESSAGE_BYTES,
        "max_progress_frame_bytes": MAX_PROGRESS_FRAME_BYTES,
        "progress_interval_ms": PROGRESS_INTERVAL_MS,
        "progress_burst": PROGRESS_BURST,
        "max_manifest_bytes": MAX_MANIFEST_BYTES,
        "max_capabilities_per_kind": MAX_CAPABILITIES_PER_KIND,
        "max_name_bytes": MAX_NAME_BYTES,
        "max_version_bytes": MAX_VERSION_BYTES,
        "max_description_bytes": MAX_DESCRIPTION_BYTES,
        "max_schema_bytes": MAX_SCHEMA_BYTES,
        "max_schema_depth": MAX_SCHEMA_DEPTH,
        "max_model_tokens": MAX_PLUGIN_MODEL_TOKENS,
        "max_price_micros_usd": MAX_PLUGIN_PRICE_MICROS_USD,
    })
}

fn render_typescript() -> String {
    let operation_types = format!(
        "export {}\nexport {}\nexport {}\n",
        OperationLifetime::decl(&ts_rs::Config::default()),
        ProgressAmount::decl(&ts_rs::Config::default()),
        ToolProgress::decl(&ts_rs::Config::default())
    );
    format!(
        "{GENERATED_MARKER}\n\n\
export const PLUGIN_PROTOCOL_VERSION = {PROTOCOL_VERSION} as const\n\
export const PLUGIN_HOST_ID = \"{PLUGIN_HOST_ID}\" as const\n\n\
export const RPC_METHODS = Object.freeze({{\n\
  initialize: \"{METHOD_INITIALIZE}\",\n\
  toolCall: \"{METHOD_TOOL_CALL}\",\n\
  toolProgress: \"{METHOD_TOOL_PROGRESS}\",\n\
  commandExecute: \"{METHOD_COMMAND_EXECUTE}\",\n\
  hookInvoke: \"{METHOD_HOOK_INVOKE}\",\n\
  providerComplete: \"{METHOD_PROVIDER_COMPLETE}\",\n\
  providerModels: \"{METHOD_PROVIDER_MODELS}\",\n\
  providerEvent: \"{METHOD_PROVIDER_EVENT}\",\n\
  providerCredit: \"{METHOD_PROVIDER_CREDIT}\",\n\
  providerHttp: \"{METHOD_PROVIDER_HTTP}\",\n\
  providerHttpEvent: \"{METHOD_PROVIDER_HTTP_EVENT}\",\n\
  providerHttpCancel: \"{METHOD_PROVIDER_HTTP_CANCEL}\",\n\
  eventPublish: \"{METHOD_EVENT_PUBLISH}\",\n\
  eventRead: \"{METHOD_EVENT_READ}\",\n\
  sessionQuery: \"{METHOD_SESSION_QUERY}\",\n\
  contextRead: \"{METHOD_SESSION_CONTEXT_READ}\",\n\
  sessionControl: \"{METHOD_SESSION_CONTROL}\",\n\
  sessionToolCall: \"{METHOD_SESSION_TOOL_CALL}\",\n\
  stateRead: \"{METHOD_EXTENSION_STATE_READ}\",\n\
  stateCommit: \"{METHOD_EXTENSION_STATE_COMMIT}\",\n\
  injectMessage: \"{METHOD_SESSION_INJECT_MESSAGE}\",\n\
  setStatus: \"{METHOD_SESSION_SET_STATUS}\",\n\
  notify: \"{METHOD_UI_NOTIFY}\",\n\
  publishPanel: \"{METHOD_UI_PUBLISH_PANEL}\",\n\
  shutdown: \"{METHOD_SHUTDOWN}\",\n\
  exit: \"{METHOD_EXIT}\",\n\
}} as const)\n\n\
export const PROTOCOL_LIMITS = {{\n\
  maxLineBytes: {MAX_FRAME_BYTES} as number,\n\
  maxManifestBytes: {MAX_MANIFEST_BYTES} as number,\n\
  maxCapabilitiesPerKind: {MAX_CAPABILITIES_PER_KIND} as number,\n\
  maxNameBytes: {MAX_NAME_BYTES} as number,\n\
  maxVersionBytes: {MAX_VERSION_BYTES} as number,\n\
  maxDescriptionBytes: {MAX_DESCRIPTION_BYTES} as number,\n\
  maxSchemaBytes: {MAX_SCHEMA_BYTES} as number,\n\
  maxSchemaDepth: {MAX_SCHEMA_DEPTH} as number,\n\
  maxRpcMessageBytes: {MAX_RPC_MESSAGE_BYTES} as number,\n\
  maxHookPayloadBytes: {MAX_HOOK_PAYLOAD_BYTES} as number,\n\
  maxModelTokens: {MAX_PLUGIN_MODEL_TOKENS} as number,\n\
  maxPriceMicrosUsd: {MAX_PLUGIN_PRICE_MICROS_USD} as number,\n\
  defaultHandlerTimeoutMs: {DEFAULT_HANDLER_TIMEOUT_MS} as number,\n\
  maxInFlightRequests: {MAX_IN_FLIGHT_REQUESTS} as number,\n\
  maxProviderStreams: {MAX_PROVIDER_STREAMS} as number,\n\
  controlQueueFrames: {CONTROL_QUEUE_FRAMES} as number,\n\
  controlQueueBytes: {CONTROL_QUEUE_BYTES} as number,\n\
  dataQueueBytes: {DATA_QUEUE_BYTES} as number,\n\
  providerWindowEvents: {PROVIDER_WINDOW_EVENTS} as number,\n\
  providerWindowBytes: {PROVIDER_WINDOW_BYTES} as number,\n\
  maxOperationDurationMs: {MAX_OPERATION_DURATION_MS} as number,\n\
  defaultToolIdleTimeoutMs: {DEFAULT_TOOL_IDLE_TIMEOUT_MS} as number,\n\
  maxProgressMessageChars: {MAX_PROGRESS_MESSAGE_CHARS} as number,\n\
  maxProgressMessageBytes: {MAX_PROGRESS_MESSAGE_BYTES} as number,\n\
  maxProgressFrameBytes: {MAX_PROGRESS_FRAME_BYTES} as number,\n\
  progressIntervalMs: {PROGRESS_INTERVAL_MS} as number,\n\
  progressBurst: {PROGRESS_BURST} as number,\n\
}} as const\n\n{operation_types}\n{TYPESCRIPT_DECLARATIONS}"
    )
}

fn render_fixture() -> Result<String, serde_json::Error> {
    let mut value: Value = serde_json::from_str(FIXTURE_TEMPLATE)?;
    value["$comment"] = json!(GENERATED_NOTICE);
    value["protocol"] = json!(PROTOCOL_VERSION);
    value["limits"] = limits();
    value["methods"] = methods();
    value["initialize_request"]["jsonrpc"] = json!(JSON_RPC_VERSION);
    value["initialize_request"]["method"] = json!(METHOD_INITIALIZE);
    value["initialize_request"]["params"]["host"] = json!(PLUGIN_HOST_ID);
    value["initialize_request"]["params"]["protocol"] = json!(PROTOCOL_VERSION);
    value["initialize_request"]["params"]["max_frame_bytes"] = json!(MAX_FRAME_BYTES);
    value["initialize_response"]["jsonrpc"] = json!(JSON_RPC_VERSION);
    value["initialize_response"]["result"]["protocol"] = json!(PROTOCOL_VERSION);
    value["provider_models_request"]["method"] = json!(METHOD_PROVIDER_MODELS);
    value["provider_http_request"]["method"] = json!(METHOD_PROVIDER_HTTP);
    value["provider_http_head"]["method"] = json!(METHOD_PROVIDER_HTTP_EVENT);
    value["provider_http_body"]["method"] = json!(METHOD_PROVIDER_HTTP_EVENT);
    value["provider_http_finished"]["method"] = json!(METHOD_PROVIDER_HTTP_EVENT);
    value["tool_call_request"] = json!({"jsonrpc": JSON_RPC_VERSION, "id": 17, "method": METHOD_TOOL_CALL,
        "params": {"name":"work","input":{},"lifetime":OperationLifetime::default()}});
    value["tool_progress"] = json!({"jsonrpc": JSON_RPC_VERSION,"method":METHOD_TOOL_PROGRESS,
        "params":{"request_id":17,"sequence":1,"progress":{"message":"working","amount":{"completed":1,"total":2}}}});
    Ok(serde_json::to_string_pretty(&value)? + "\n")
}

fn render_schema() -> Result<String, serde_json::Error> {
    let mut value: Value = serde_json::from_str(SCHEMA_TEMPLATE)?;
    value["$comment"] = json!(GENERATED_NOTICE);
    value["properties"]["$comment"] = json!({ "const": GENERATED_NOTICE });
    if let Some(required) = value["required"].as_array_mut()
        && !required.iter().any(|entry| entry == "$comment")
    {
        required.insert(0, json!("$comment"));
    }
    value["properties"]["protocol"]["const"] = json!(PROTOCOL_VERSION);
    if let Some(properties) = value["properties"]["limits"]["properties"].as_object_mut() {
        let current = limits();
        for (name, limit) in current.as_object().into_iter().flatten() {
            properties.insert(name.clone(), json!({"const":limit}));
        }
    }
    value["properties"]["limits"]["required"] = json!(
        limits()
            .as_object()
            .map(|limits| limits.keys().cloned().collect::<Vec<_>>())
            .unwrap_or_default()
    );
    value["$defs"]["operation_lifetime"] =
        serde_json::to_value(schemars::schema_for!(OperationLifetime))?;
    let mut progress = serde_json::to_value(schemars::schema_for!(ToolProgress))?;
    if let Some(definitions) = progress
        .as_object_mut()
        .and_then(|schema| schema.remove("$defs"))
    {
        for (name, definition) in definitions.as_object().into_iter().flatten() {
            value["$defs"][name] = definition.clone();
        }
    }
    value["$defs"]["tool_progress"] = progress;
    value["properties"]["tool_call_request"] = json!({"$ref":"#/$defs/request"});
    value["properties"]["tool_progress"] = json!({"$ref":"#/$defs/notification"});
    value["$defs"]["id"]["oneOf"][1]["maxLength"] = json!(MAX_NAME_BYTES);
    value["$defs"]["request"]["properties"]["jsonrpc"]["const"] = json!(JSON_RPC_VERSION);
    value["$defs"]["request"]["properties"]["method"]["maxLength"] = json!(MAX_NAME_BYTES);
    value["$defs"]["success"]["properties"]["jsonrpc"]["const"] = json!(JSON_RPC_VERSION);
    value["$defs"]["notification"]["properties"]["jsonrpc"]["const"] = json!(JSON_RPC_VERSION);
    value["$defs"]["notification"]["properties"]["method"]["maxLength"] = json!(MAX_NAME_BYTES);
    value["$defs"]["initialize_params"]["properties"]["host"]["const"] = json!(PLUGIN_HOST_ID);
    Ok(serde_json::to_string_pretty(&value)? + "\n")
}

fn ensure_output(path: &Path, expected: &str, check: bool) -> Result<(), String> {
    if check {
        let actual =
            fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
        if actual != expected {
            return Err(format!(
                "{} is stale; run cargo xtask codegen",
                path.display()
            ));
        }
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| format!("{}: {error}", parent.display()))?;
    }
    fs::write(path, expected).map_err(|error| format!("{}: {error}", path.display()))
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

pub(super) fn run(check: bool) -> Result<(), String> {
    let root = repo_root();
    shared_types::generate(&root, check)?;
    ensure_output(
        &root.join("packages/plugin-sdk/src/generated/protocol-3.ts"),
        &render_typescript(),
        check,
    )?;
    ensure_output(
        &root.join("packages/plugin-sdk/fixtures/wire/protocol-3.json"),
        &render_fixture().map_err(|error| error.to_string())?,
        check,
    )?;
    ensure_output(
        &root.join("packages/plugin-sdk/fixtures/wire/protocol-3.schema.json"),
        &render_schema().map_err(|error| error.to_string())?,
        check,
    )?;
    Ok(())
}
