import { readFile, writeFile } from "node:fs/promises"
import { standaloneValidator } from "../tui/scripts/standalone-validator"

const check = process.argv.includes("--check")
const schemas: readonly (readonly [string, string])[] = [["hook-input", "HookInput"], ["hook-directive", "HookDirective"]]
for (const [name, typeName] of schemas) {
  const schema: unknown = JSON.parse(await readFile(new URL(`fixtures/wire/${name}.schema.json`, import.meta.url), "utf8"))
  if (typeof schema !== "object" || schema === null) throw new Error("hook schema must be an object")
  const generated = await standaloneValidator({ schema, typeName, typeImport: "./hook-contract", banner: "// @generated by generate-hook-validators.ts; do not edit by hand.\n" })
  const outputs: readonly (readonly [string, string])[] = [["js", generated.javascript], ["d.ts", generated.declaration]]
  for (const [extension, content] of outputs) {
    const path = new URL(`src/generated/${name}-validator.${extension}`, import.meta.url)
    if (check) {
      if (await readFile(path, "utf8") !== content) throw new Error(`${path.pathname} is out of date`)
    } else { await writeFile(path, content) }
  }
}
