import { readFile, writeFile } from "node:fs/promises"
import { standaloneValidator } from "../tui/scripts/standalone-validator"

const check = process.argv.includes("--check")
const schemas: readonly (readonly [string, string, string])[] = [
  ["tool-response", "ToolResponse", "tool-contract"],
  ["extension-tool-call", "ExtensionToolCall", "extension-contract"],
  ["extension-effect-call", "ExtensionEffectCall", "extension-contract"],
  ["extension-tool-outcome", "ExtensionToolOutcome", "extension-contract"],
  ["ui-panel-update", "UiPanelUpdate", "ui-contract"],
  ["ui-panel-updated", "UiPanelUpdated", "ui-contract"],
  ["ui-contribution", "UiContribution", "ui-contract"],
  ["extension-event-kind", "ExtensionEventKind", "extension-contract"],
  ["extension-event-notice", "ExtensionEventNotice", "extension-contract"],
  ["extension-event-outcome", "ExtensionEventOutcome", "extension-contract"],
  ["extension-event-chunk", "ExtensionEventChunk", "extension-contract"],

  ["hook-input", "HookInput", "hook-contract"],
  ["hook-directive", "HookDirective", "hook-contract"],
  ["provider-request", "ProviderRequest", "provider-contract"],
  ["provider-event", "ProviderEvent", "provider-contract"],
  ["extension-state-transaction", "ExtensionStateTransaction", "extension-contract"],
  ["extension-state-snapshot", "ExtensionStateSnapshot", "extension-contract"],
  ["extension-state-outcome", "ExtensionStateCommitOutcome", "extension-contract"],
  ["extension-context-read", "ExtensionContextRead", "extension-contract"],
  ["extension-context-page", "ExtensionContextPage", "extension-contract"],
  ["extension-control", "ExtensionControl", "extension-contract"],
  ["extension-invocation-id", "ExtensionInvocationId", "extension-contract"],
  ["extension-control-outcome", "ExtensionControlOutcome", "extension-contract"],
  ["extension-session-snapshot", "ExtensionSessionSnapshot", "extension-contract"],
]
for (const [name, typeName, contract] of schemas) {
  const schema: unknown = JSON.parse(await readFile(new URL(`fixtures/wire/${name}.schema.json`, import.meta.url), "utf8"))
  if (typeof schema !== "object" || schema === null) throw new Error("plugin schema must be an object")
  const generated = await standaloneValidator({ schema, typeName, typeImport: `./${contract}`, banner: "// @generated by generate-contract-validators.ts; do not edit by hand.\n" })
  let javascript = generated.javascript
  let declaration = generated.declaration
  if (name === "provider-event") {
    const alternatives = (schema as { oneOf?: unknown }).oneOf
    if (!Array.isArray(alternatives) || alternatives.length === 0) throw new Error("ProviderEvent must be a closed record union")
    const fields = new Set<string>()
    for (const alternative of alternatives) {
      if (typeof alternative !== "object" || alternative === null || alternative.type !== "object"
        || alternative.additionalProperties !== false || typeof alternative.properties !== "object"
        || alternative.properties === null || Array.isArray(alternative.properties)) {
        throw new Error("ProviderEvent alternatives must declare closed record properties")
      }
      for (const field of Object.keys(alternative.properties)) fields.add(field)
    }
    javascript += `\nexport const PROVIDER_EVENT_FIELDS = Object.freeze(${JSON.stringify([...fields].sort())});\n`
    declaration += "export const PROVIDER_EVENT_FIELDS: readonly string[];\n"
  }
  const outputs: readonly (readonly [string, string])[] = [["js", javascript], ["d.ts", declaration]]
  for (const [extension, content] of outputs) {
    const path = new URL(`src/generated/${name}-validator.${extension}`, import.meta.url)
    if (check) {
      if (await readFile(path, "utf8") !== content) throw new Error(`${path.pathname} is out of date`)
    } else { await writeFile(path, content) }
  }
}
