[package]
name = "xtask"
description = "Repository build and code-generation tasks for Rottweiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
rw-types.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ts-rs.workspace = true

[lints]
workspace = true
