import importlib.util
from pathlib import Path
import tempfile
import textwrap
import unittest


REPO_ROOT = Path(__file__).resolve().parents[2]
CHECKER_PATH = REPO_ROOT / "scripts" / "check-ownership.py"


def load_checker():
    spec = importlib.util.spec_from_file_location("ownership", CHECKER_PATH)
    if spec is None or spec.loader is None:
        raise AssertionError("ownership checker cannot be loaded")
    checker = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(checker)
    return checker


def write(root: Path, relative_path: str, contents: str = "") -> None:
    path = root / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def valid_manifest(extra: str = "") -> str:
    return textwrap.dedent(
        f'''\
        version = 1

        [[owner]]
        id = "session-protocol"
        path = "src/protocol.rs"
        symbols = ["SessionId::validate"]

        [[generator]]
        id = "session-protocol-typescript"
        owner = "session-protocol"
        command = "tool codegen --check"
        marker = "// @generated by tool codegen; do not edit."
        outputs = ["generated/protocol.ts"]

        [[shadow]]
        id = "legacy-session-validator"
        owner = "session-protocol"
        path = "client/session.ts"
        pattern = "function\\\\s+validateSessionId\\\\s*\\\\("
        reason = "Clients consume the protocol projection."

        {extra}
        '''
    )


class OwnershipCheckerTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.checker = load_checker()

    def make_valid_repository(self, root: Path) -> Path:
        write(root, "src/protocol.rs", "impl SessionId { fn validate() {} }\n")
        write(
            root,
            "generated/protocol.ts",
            "// @generated by tool codegen; do not edit.\n",
        )
        write(root, "client/session.ts", "export function connect() {}\n")
        manifest = root / "architecture" / "ownership.toml"
        write(root, "architecture/ownership.toml", valid_manifest())
        return manifest

    def test_valid_manifest_is_accepted(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)

            self.assertEqual(self.checker.validate_repository(root, manifest), [])

    def test_duplicate_owner_path_owner_id_and_generator_id_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)
            manifest.write_text(
                valid_manifest(
                    '''
                    [[owner]]
                    id = "other-owner"
                    path = "src/protocol.rs"
                    symbols = ["Other"]

                    [[owner]]
                    id = "session-protocol"
                    path = "src/other.rs"
                    symbols = ["Other"]

                    [[generator]]
                    id = "session-protocol-typescript"
                    owner = "other-owner"
                    command = "other codegen --check"
                    marker = "// @generated by other codegen; do not edit."
                    outputs = ["generated/other.ts"]
                    '''
                ),
                encoding="utf-8",
            )
            write(root, "src/other.rs", "struct Other;\n")
            write(root, "generated/other.ts", "// @generated by other codegen; do not edit.\n")

            failures = self.checker.validate_repository(root, manifest)

            self.assertTrue(any("owner path" in failure for failure in failures))
            self.assertTrue(any("owner id" in failure for failure in failures))
            self.assertTrue(any("generator id" in failure for failure in failures))

    def test_missing_owner_symbol_and_generated_marker_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)
            write(root, "src/protocol.rs", "pub struct SessionId(String);\n")
            write(root, "generated/protocol.ts", "export type SessionId = string\n")

            failures = self.checker.validate_repository(root, manifest)

            self.assertTrue(any("owner symbol" in failure for failure in failures))
            self.assertTrue(any("generated marker" in failure for failure in failures))

    def test_generated_markers_identify_one_generator(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)
            manifest.write_text(
                valid_manifest(
                    '''
                    [[owner]]
                    id = "other-owner"
                    path = "src/other.rs"
                    symbols = ["Other"]

                    [[generator]]
                    id = "other-generator"
                    owner = "other-owner"
                    command = "other codegen --check"
                    marker = "// @generated by tool codegen; do not edit."
                    outputs = ["generated/other.ts"]
                    '''
                ),
                encoding="utf-8",
            )
            write(root, "src/other.rs", "struct Other;\n")
            write(root, "generated/other.ts", "// @generated by tool codegen; do not edit.\n")

            failures = self.checker.validate_repository(root, manifest)

            self.assertTrue(any("generated marker" in failure for failure in failures))

    def test_forbidden_shadow_definition_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)
            write(root, "client/session.ts", "function validateSessionId(value: string) {}\n")

            failures = self.checker.validate_repository(root, manifest)

            self.assertTrue(any("legacy-session-validator" in failure for failure in failures))

    def test_owner_and_output_paths_must_be_safe_and_unique(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = self.make_valid_repository(root)
            manifest.write_text(
                valid_manifest(
                    '''
                    [[owner]]
                    id = "outside"
                    path = "../outside.rs"
                    symbols = ["Outside"]

                    [[generator]]
                    id = "duplicate-output"
                    owner = "outside"
                    command = "other codegen --check"
                    marker = "// @generated by other codegen; do not edit."
                    outputs = ["generated/protocol.ts"]
                    '''
                ),
                encoding="utf-8",
            )

            failures = self.checker.validate_repository(root, manifest)

            self.assertTrue(any("safe repository-relative path" in failure for failure in failures))
            self.assertTrue(any("generated output" in failure for failure in failures))

    def test_repository_manifest_is_valid(self) -> None:
        failures = self.checker.validate_repository(
            REPO_ROOT,
            REPO_ROOT / "architecture" / "ownership.toml",
        )
        self.assertEqual(failures, [])

    def test_ci_and_release_run_the_ownership_check_with_architecture_gates(self) -> None:
        ci = (REPO_ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
        release = (REPO_ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
        gates = [
            "python3 scripts/check-dependency-direction.py",
            "python3 scripts/check-ownership.py",
            "python3 scripts/check-toolchain-ownership.py",
            "python3 scripts/check-network-boundaries.py",
        ]
        for workflow in (ci, release):
            positions = [workflow.find(gate) for gate in gates]
            self.assertTrue(all(position >= 0 for position in positions))
            self.assertEqual(positions, sorted(positions))


if __name__ == "__main__":
    unittest.main()
