//! Durable envelope projection from the public event contract and storage version.

use rw_types::EngineEvent;
use schemars::schema_for;
use serde_json::json;

use crate::XtaskError;

pub(super) fn generate() -> Result<String, XtaskError> {
    let schema = serde_json::to_value(schema_for!(EngineEvent))?;
    let variants = schema
        .get("oneOf")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| XtaskError::GeneratedContract("EngineEvent has no variants".to_owned()))?;
    let mut excluded = Vec::new();
    for variant in variants {
        if variant
            .pointer("/properties/meta/$ref")
            .and_then(serde_json::Value::as_str)
            == Some("#/$defs/CommandAckMeta")
        {
            let tag = variant
                .pointer("/properties/type/const")
                .and_then(serde_json::Value::as_str)
                .ok_or_else(|| {
                    XtaskError::GeneratedContract("EngineEvent variant has no type tag".to_owned())
                })?;
            excluded.push(tag);
        }
    }
    excluded.sort_unstable();
    let envelope = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "SessionEventEnvelope",
        "description": "One record in Rottweiler's append-only durable session JSONL log.",
        "type": "object",
        "required": [
            "schema_version",
            "sequence",
            "event"
        ],
        "$defs": {
            "SequenceId": {
                "type": "string",
                "maxLength": 20,
                "pattern": "^(?:0|[1-9][0-9]{0,18}|1[0-7][0-9]{18}|18[0-3][0-9]{17}|184[0-3][0-9]{16}|1844[0-5][0-9]{15}|18446[0-6][0-9]{14}|184467[0-3][0-9]{13}|1844674[0-3][0-9]{12}|184467440[0-6][0-9]{10}|1844674407[0-2][0-9]{9}|18446744073[0-6][0-9]{8}|1844674407370[0-8][0-9]{6}|18446744073709[0-4][0-9]{5}|184467440737095[0-4][0-9]{4}|18446744073709550[0-9]{3}|18446744073709551[0-5][0-9]{2}|1844674407370955160[0-9]{1}|1844674407370955161[0-4]|18446744073709551615)$"
            }
        },
        "properties": {
            "schema_version": {
                "const": rw_store::session::SESSION_EVENT_SCHEMA_VERSION,
                "description": "Durable event-log envelope version."
            },
            "sequence": {
                "$ref": "#/$defs/SequenceId",
                "description": "Decimal-string encoded contiguous zero-based sequence within one session."
            },
            "event": {
                "description": "Provider- and UI-neutral durable engine event payload. Connection-scoped acknowledgements without a session sequence are not durable events.",
                "allOf": [
                    {
                        "$ref": "schema/engine-event.schema.json"
                    },
                    {
                        "type": "object",
                        "required": [
                            "meta"
                        ],
                        "properties": {
                            "meta": {
                                "type": "object",
                                "required": [
                                    "sequence_id"
                                ],
                                "properties": {
                                    "sequence_id": {
                                        "$ref": "#/$defs/SequenceId"
                                    }
                                }
                            }
                        },
                        "not": {
                            "type": "object",
                            "required": [
                                "type"
                            ],
                            "properties": {
                                "type": {
                                    "enum": excluded
                                }
                            }
                        }
                    }
                ]
            }
        },
        "additionalProperties": false,
        "$comment": "@generated by cargo xtask codegen; do not edit."
    });
    Ok(serde_json::to_string_pretty(&envelope)? + "\n")
}
