#![cfg(test)]
#![allow(clippy::expect_used)]

mod attachments;
mod budget;
mod cancellation;
mod close;
mod command_copy;
mod command_lifetime;
mod commands;
mod compaction;
mod compaction_recovery;
mod completion_hooks;
mod context;
mod control_admission;
mod diff_approval;
mod doom_loop;
mod event_batches;
mod fixtures;
mod generation_lifetime;
mod hooks;
mod model_preparation;
mod model_selection;
mod modes;
mod mutation_checkpoints;
mod navigation;
mod permissions;
mod persistence;
mod plan;
mod plugin_capability;
mod protocol_control;
mod provider_usage;
mod questions;
mod reasoning;
mod recovery;
mod redaction;
mod rewind;
mod shell;
mod snapshots;
mod startup;
mod subagents;
mod subscription;
mod titles;
mod todos;
mod tool_admission;
mod tool_order;
mod ui_actions;

mod citations;
