[package]
name = "rw-sandbox"
description = "OS-native process sandboxing for Rottweiler"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rw-types.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.4.5"
libc = "0.2.183"
seccompiler = "0.5.0"

[dev-dependencies]
tempfile = "3.23"

[lints]
workspace = true
