pub use crate::storage_root::initialize_private_storage_root;
mod accounting_projection;
mod checkpoint_journal;
mod checkpoints;
mod code_intelligence;
mod command_execution;
mod credential_resolution;
mod custom_commands;
mod declarative_hooks;
mod deferred_network;
mod durable_session;
mod extension_discovery;
mod folder_trust;
mod fork_storage;
mod headless_lifetime;
mod headless_session;
mod hosted_composition;
mod initial_memory;
mod interaction_policy;
mod local_session;
mod model_effects;
mod model_selection;
pub(crate) mod native_model_generations;
pub(crate) mod native_registry_recipe;
pub(crate) mod native_search;
mod nested_instructions;
pub(crate) mod plugin_event_fanout;
mod prompt_model;
mod prompt_shapes;
mod provider_activation;
mod provider_adapter;
mod provider_catalog;
mod runtime_options;
mod script_provider;
mod secret_redaction;
mod session_metadata;
mod session_selection;
mod subagent_recovery;
mod subagent_runtime;
pub(crate) mod tool_composition;
mod toolchain;
mod wasm_hooks;
mod web_fetch;
mod websearch_recording;
pub(crate) mod workspace_roots;
use checkpoint_journal::REWIND_COORDINATOR_VERSION;
use checkpoint_journal::RewindCoordinatorDecision;
use checkpoint_journal::RewindCoordinatorState;
pub(crate) use checkpoint_journal::load_checkpoint_roots_exact;
use checkpoint_journal::load_rewind_coordinator;
pub(crate) use checkpoint_journal::load_session_workspace_roots;
use checkpoint_journal::persist_rewind_coordinator;
use checkpoint_journal::remove_rewind_coordinator;
use checkpoint_journal::validate_rewind_coordinator;
use credential_resolution::ResolvedToolProxy;
pub use extension_discovery::discover_runtime_extensions;
pub use extension_discovery::extension_user_roots;
pub(crate) use fork_storage::fork_hosted_session_storage;
pub(crate) use fork_storage::remove_forked_session_storage;
pub(crate) use fork_storage::validate_forked_session_commit;
pub use headless_session::compose_local_session;
pub(crate) use hosted_composition::compose_hosted_actor;
pub use local_session::LocalSession;
pub use provider_catalog::discover_model_catalog;
pub use runtime_options::HostedProviderMode;
pub(crate) use runtime_options::HostedSessionComposition;
pub use runtime_options::LocalSessionOptions;
pub use runtime_options::LocalSessionPurpose;
use runtime_options::MAX_GLOBAL_REVIEW_DIFF_BYTES;
use runtime_options::MAX_GLOBAL_REVIEW_FILES;
use runtime_options::MAX_WORKSPACE_ROOTS;
pub use secret_redaction::register_credential_environment;
pub use session_metadata::load_inherited_accounting_boundary_bounded;
pub(crate) use session_metadata::load_session_metadata_any;
pub use session_metadata::new_session_id;
#[cfg(not(unix))]
use session_metadata::persist_session_metadata_portable;
pub(crate) use session_selection::checkpoint_root;
pub use session_selection::select_interactive_session;
pub use wasm_hooks::locate_wasm_host_executable;
#[cfg(test)]
mod tests;

mod search_projection;
