[package]
name = "rw-cli"
description = "Rottweiler command-line entry point"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "rw"
path = "src/main.rs"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.89"
base64.workspace = true
blake3.workspace = true
clap.workspace = true
flate2.workspace = true
futures-util = "0.3.31"
getrandom.workspace = true
globset.workspace = true
ignore.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
miette.workspace = true
nix = { workspace = true, features = ["event"] }
portable-pty.workspace = true
rpassword.workspace = true
rw-core.workspace = true
rw-ext.workspace = true
rw-mcp.workspace = true
rw-plugin-protocol.workspace = true
rw-providers.workspace = true
rw-resources.workspace = true
rw-runtime.workspace = true
rw-store.workspace = true
rw-tools.workspace = true
rw-types.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
shell-words.workspace = true
tokio.workspace = true
tar.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
toml.workspace = true

[dev-dependencies]
nix = { workspace = true, features = ["term"] }
ed25519-dalek.workspace = true
rmcp.workspace = true
tempfile = "3.23"

[lints]
workspace = true
