import { readFile, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import eventSchema from "../../../protocol/schema/engine-event.schema.json"
import replySchema from "../../../protocol/schema/command-reply.schema.json"
import { standaloneValidator } from "./standalone-validator"

const root = new URL("../../../protocol/", import.meta.url)
for (const { schema, name, typeName } of [
  { schema: eventSchema, name: "engine-event", typeName: "EngineEvent" },
  { schema: replySchema, name: "command-reply", typeName: "CommandReply" },
]) {
  const { javascript, declaration } = await standaloneValidator({
    schema, typeName, typeImport: "./types",
    banner: "// @generated by `cargo xtask codegen`; do not edit by hand.\n",
  })
  const artifacts = [
    [`${name}-validator.js`, javascript],
    [`${name}-validator.d.ts`, declaration],
  ] as const
  for (const [name, contents] of artifacts) {
    const url = new URL(name, root)
    if (process.argv.includes("--check")) {
      if (await readFile(url, "utf8") !== contents) {
        throw new Error(`generated artifact is stale: ${fileURLToPath(url)}`)
      }
    } else {
      await writeFile(url, contents)
    }
  }
}
