import { readFile, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import Ajv2020 from "ajv/dist/2020"
import standaloneCode from "ajv/dist/standalone"
import schema from "../../../protocol/schema/engine-event.schema.json"

const root = new URL("../../../protocol/", import.meta.url)
const bunVersion = (await readFile(new URL("../.bun-version", root), "utf8")).trim()
if (Bun.version !== bunVersion) throw new Error(`validator generation requires Bun ${bunVersion}`)
const ajv = new Ajv2020({
  code: { source: true, esm: true, lines: true },
  discriminator: true,
  inlineRefs: false,
  allErrors: false,
  messages: false,
  // Schemars' numeric format names are annotations; its type/min/max constraints
  // remain enforced. Runtime protocol version and u64 cursors use shared owners.
  validateFormats: false,
})
// All top-level event variants have a required, unique type discriminator.
// Ajv verifies that condition and generates dispatch instead of trying every variant.
const validate = ajv.compile({
  ...schema,
  type: "object",
  required: ["type"],
  discriminator: { propertyName: "type" },
})
const banner = "// @generated by `cargo xtask codegen`; do not edit by hand.\n"
const artifacts = [
  ["engine-event-validator.js", banner + standaloneCode(ajv, validate)],
  ["engine-event-validator.d.ts", `${banner}import type { EngineEvent } from "./types";\nexport default function validateEngineEvent(value: unknown): value is EngineEvent;\n`],
] as const
const check = process.argv.includes("--check")
for (const [name, contents] of artifacts) {
  const url = new URL(name, root)
  if (check) {
    if (await readFile(url, "utf8") !== contents) {
      throw new Error(`generated artifact is stale: ${fileURLToPath(url)}`)
    }
  } else {
    await writeFile(url, contents)
  }
}
