import { readFile, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import Ajv2020 from "ajv/dist/2020"
import standaloneCode from "ajv/dist/standalone"
import eventSchema from "../../../protocol/schema/engine-event.schema.json"
import replySchema from "../../../protocol/schema/command-reply.schema.json"

function schemaObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

/** Derive every tagged union dispatch from the Rust schema, including reply events. */
function addDiscriminators(value: unknown): void {
  if (Array.isArray(value)) {
    for (const child of value) addDiscriminators(child)
    return
  }
  if (!schemaObject(value)) return
  for (const child of Object.values(value)) addDiscriminators(child)
  const variants = value.oneOf
  if (!Array.isArray(variants) || variants.length === 0) return
  const tags = new Set<string>()
  for (const variant of variants) {
    if (!schemaObject(variant) || !schemaObject(variant.properties)
      || !schemaObject(variant.properties.type) || typeof variant.properties.type.const !== "string"
      || !Array.isArray(variant.required) || !variant.required.includes("type")) return
    tags.add(variant.properties.type.const)
  }
  if (tags.size !== variants.length) return
  value.type = "object"
  value.discriminator = { propertyName: "type" }
}

const root = new URL("../../../protocol/", import.meta.url)
const bunVersion = (await readFile(new URL("../.bun-version", root), "utf8")).trim()
if (Bun.version !== bunVersion) throw new Error(`validator generation requires Bun ${bunVersion}`)
for (const { schema, name, type } of [
  { schema: eventSchema, name: "engine-event", type: "EngineEvent" },
  { schema: replySchema, name: "command-reply", type: "CommandReply" },
]) {
  const ajv = new Ajv2020({
    code: { source: true, esm: true, lines: true },
    discriminator: true,
    inlineRefs: false,
    allErrors: false,
    messages: false,
    // Schemars' numeric format names are annotations; its type/min/max constraints
    // remain enforced. Runtime protocol version and u64 cursors use shared owners.
    validateFormats: false,
  })
  const prepared = structuredClone(schema)
  addDiscriminators(prepared)
  const validate = ajv.compile(prepared)
  // AJV emits runtime imports for Unicode length checks. Bundle those helpers so
  // the generated protocol artifact is independent of consumer dependency layout.
  const generated = standaloneCode(ajv, validate)
  const bundled = await Bun.build({
    entrypoints: ["rottweiler:engine-event-validator"],
    root: fileURLToPath(new URL("../", import.meta.url)),
    target: "browser",
    format: "esm",
    minify: { whitespace: true, syntax: true, identifiers: false },
    plugins: [{ name: "generated-event-validator", setup(build) {
      build.onResolve({ filter: /^rottweiler:/ }, () => ({ path: "engine-event-validator.js", namespace: "generated" }))
      build.onLoad({ filter: /.*/, namespace: "generated" }, () => ({ contents: generated, loader: "js" }))
      build.onResolve({ filter: /^ajv\// }, args => ({ path: fileURLToPath(import.meta.resolve(args.path)) }))
    } }],
  })
  if (!bundled.success || bundled.outputs.length !== 1) throw new Error("standalone event validator bundling failed")
  const executable = await bundled.outputs[0]?.text()
  if (executable === undefined) throw new Error("standalone event validator output missing")
  const banner = "// @generated by `cargo xtask codegen`; do not edit by hand.\n"
  const artifacts = [
    [`${name}-validator.js`, banner + executable],
    [`${name}-validator.d.ts`, `${banner}import type { ${type} } from "./types";\nexport default function validate(value: unknown): value is ${type};\n`],
  ] as const
  const check = process.argv.includes("--check")
  for (const [name, contents] of artifacts) {
    const url = new URL(name, root)
    if (check) {
      if (await readFile(url, "utf8") !== contents) {
        throw new Error(`generated artifact is stale: ${fileURLToPath(url)}`)
      }
    } else {
      await writeFile(url, contents)
    }
  }

}
