import type {
  ClientCommand as GeneratedClientCommand,
  EngineEvent as GeneratedEngineEvent,
} from "../../../protocol/types"

export {
  ENGINE_EVENT_DELIVERY,
  MAX_COMMAND_REPLY_BYTES,
  MAX_ATTACHMENTS_PER_MESSAGE,
  MAX_IMAGE_ATTACHMENT_BYTES,
  MAX_MCP_SERVER_ID_BYTES,
  MAX_TEXT_ATTACHMENT_BYTES,
  MAX_TOTAL_ATTACHMENT_BYTES,
  MCP_SERVER_ID_PATTERN,
  PROTOCOL_VERSION,
} from "../../../protocol/types"
export type {
  Answer,
  Attachment,
  AttachmentData,
  ApprovalBinding,
  ApprovalDecision,
  BudgetLevel,
  BudgetScope,
  BudgetUnit,
  ClientRole,
  CommandOutcome,
  CommandReply,
  TranscriptOrdinal,
  TranscriptGeneration,
  TranscriptView,
  TranscriptPosition,
  TranscriptRead,
  TranscriptItem,
  TranscriptInvalidation,
  TranscriptAnchor,
  TranscriptPage,
  TranscriptReadResult,
  TranscriptContentRead,
  TranscriptContentPage,
  TranscriptItemId,
  TranscriptContentSelector,
  TranscriptContentSource,
  TranscriptPreviewFormat,
  TranscriptBodyPreview,
  TranscriptConversationBlock,
  TranscriptToolStatus,
  TranscriptSubagentStatus,
  TranscriptContent,

  CommandSource,
  ContextSnapshot,
  Cost,
  CostSnapshot,
  EngineError,
  EngineEventDelivery,
  McpApprovalReview,
  McpServerDescriptor,
  McpServerState,
  ModeDescriptor,
  PromptDump,
  PlanArtifact,
  PlanDecision,
  PlanStep,
  PermissionDecision,
  PermissionApprovalDescriptor,
  PermissionApprovalScope,
  PermissionModeDescriptor,
  PermissionRuleDescriptor,
  PermissionStateDescriptor,
  RuntimeServiceDescriptor,
  RuntimeServiceKind,
  ProviderAuthKind,
  ProviderAuthAttemptId,
  ProviderAuthChallenge,
  ProviderDescriptor,
  ProviderNextAction,
  Question,
  ReviewFileDecision,
  ReviewFileStatus,
  SessionReview,
  SessionReviewFile,
  SubagentResult,
  SubagentStatus,
  ToolCapability,
  ToolOutput,
  ToolOutputStream,
  Turn,
  TurnStatus,
  UserSettingDescriptor,
  ModeId,
  Usage,
  UnifiedDiff,
} from "../../../protocol/types"

/**
 * The TUI only consumes protocol types generated from the Rust source of truth.
 * Keeping this boundary in one module makes that ownership explicit and gives
 * the future transport client a stable local import.
 */
export type ClientCommand = GeneratedClientCommand
export type EngineEvent = GeneratedEngineEvent
